<?php

namespace App\Models\Mat_Doc\invoice;

use Illuminate\Database\Eloquent\Model;

class invoice_detail extends Model
{
    protected $connection = 'mysql_mkt_qr';
    protected $table = 'invoice_detail';
    protected $primaryKey = 'id';

    protected $fillable = [
        'id',
        'buyer',
        'invoice_final_id',
        'buyer_detail',
        'invoice_title',
        'address',
        'country',
        'telp',
        'company_bene',
        'address_bene',
        'city_bene',
        'country_bene',
        'telp_bene',
        'consigne',
        'cons_shipto',
        'cons_street',
        'cons_gate',
        'address_cons',
        'shipto',
        'country_cons',
        'container_no',
        'seal_no',
        'container_no2',
        'container_no3',
        'seal_no2',
        'buyer_for',
        'address_for',
        'country_for',
        'telp_for',
        'manufacture_name',
        'address_manu',
        'country_manu',
        'telp_manu',
        'mid_manu',
        'vessel_name',
        'shipOnBoard',
        'delivery_terms',
        'invoice_no',
        'date',
        'exp_no',
        'date_exp',
        'partOfLoading',
        'partOfDestination',
        'company_eksp',
        'address_eksp',
        'city_eksp',
        'country_eksp',
        'company_ship',
        'addres_ship',
        'city_ship',
        'country_ship',
        'ref_no',
        'contract_no',
        'buyer_notif',
        'shipto_notif',
        'street_notif',
        'gate_notif',
        'address_notif',
        'country_notif',
        'carrier',
        'salling',
        'remarks',
        'nego_bank',
        'remark_bank',
        'delive_bank',
        'payment',
        'advance',
        'date_lc',
        'lc_no',
        'carrier_deliv',
        'issued_by',
        'date_delive',
        'lc_deliv',
        'deliver_terms_del',
        'visel_name',
        'final_deliv',
        'partOfLoading_deliv',
        'date_deliv',
        'invoice_deliv',
        'deliver',
        'country_lc',
        'date_invoice',
        'bl_no',
        'date_bl',
        'bank_detail',
        'bene_name',
        'bank_name',
        'bank_address',
        'bank_acc',
        'bank_swift',
        'date_contract',
        'country_of_origin',
        'port_of_delivery',
        'created_by',
    ];
   
}
